# Generated by Django 3.2.3 on 2021-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0006_aeropuerto_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='ciudad',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='codigo',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
